plugins {
	id 'java'
	id 'org.springframework.boot' version '3.2.9'
	id 'io.spring.dependency-management' version '1.1.6'
}

group = 'GBFH'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// security
	implementation 'org.springframework.boot:spring-boot-starter-security'

	// JWT
	implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
	implementation 'io.jsonwebtoken:jjwt-impl:0.12.3'
	implementation 'io.jsonwebtoken:jjwt-jackson:0.12.3'

	// Spring Cache 의존성
	implementation 'org.springframework.boot:spring-boot-starter-cache'

	// Caffeine Cache 의존성
	implementation 'com.github.ben-manes.caffeine:caffeine'

	// s3
	implementation 'org.springframework.cloud:spring-cloud-starter-aws:2.2.6.RELEASE'

	// valid
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	//유효성 검사
	implementation 'jakarta.validation:jakarta.validation-api:3.0.0'

	// redis
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'

	// 요소 분리
	dependencies {
		implementation 'org.jsoup:jsoup:1.15.3'  // 최신 버전으로 설정
	}

	dependencies {
		implementation 'net.datafaker:datafaker:2.0.2'
	}


	// mapper
	implementation 'org.mapstruct:mapstruct:1.5.5.Final'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

	// sql
	implementation 'com.mysql:mysql-connector-j:8.0.33'


    // 랜덤 아이디 생성
    implementation 'org.apache.commons:commons-lang3:3.13.0'

}

tasks.named('test') {
	useJUnitPlatform()
}
